development:
  adapter: postgresql
  encoding: unicode
  database: menumaster_development
  pool: 5
  username: menumaster
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: menumaster_test
  pool: 5
  username: menumaster
  password: password
  host: localhost
  port: 5432

